### ISSUE TITLE
Question on bindhttp config parameter

### ISSUE THREAD

**Issue by tleyden** [couchbaselabs/cbgt#1]
@steveyen can you refresh me on what [bindhttp](https://github.com/couchbaselabs/cbgt/blob/f79472ec78c0f63afa29d9998c7221bf83f997e3/cmd/main_cfg.go#L30) is used for?

Also:
- Does it need to be routable, or does it just have to be unique for each node?
- Is there any way to have this "auto-discovered" rather than forcing users to explicitly configure it on a per-node basis?

**Comment by mschoch** [comment]
From the comments it sounds like it needs to be routable at least from the other nodes.  Its how nodes will advertise themselves to one another, so if its not routable (at least amongst themselves) its useless.

Discovering this address is the eternal pain that every distributed server process faces...

**Comment by steveyen** [comment]
bindHttp (IP-ADDR:PORT) is unique address for each node.

If you don't use the REST facilities (which actually listen on that bindHttp / see http://godoc.org/github.com/couchbaselabs/cbgt/rest#InitRESTRouter), then I guess bindHttp doesn't need to be actually "routable" and only needs to be unique for each node (so, it might work for bindHttp to be completely artificial).  Going to throw the YMMV card here, though, as that theory is very much untested.

Related to address discovery... I guess more golang code can be written to have the IP-ADDR:PORT to be auto-discoverable, and probably there's some code out there already somewhere on the open-source internets that does this already... I didn't write it yet as I expect there's cross-platform issues & intricacies (e.g., windows OS) and when machine has >1 network interfaces.

For cbft, for example, I was hoping that ns-server would just spawn the cbft processes with the right bindHttp value.

**Comment by mschoch** [comment]
Will scatter gather queries try to connect to these addresses though?

**Comment by steveyen** [comment]
> Will scatter gather queries try to connect to these addresses though?

Yes, they will, but I think in Traun's use case (prototype thoughts on a distributed/clustered sync-gateway), the thinking is that he won't every use queries, ever.

So, he's more attempting the thought exercise to perhaps use cbgt as a way to distribute DCP vbucket processing across 1 or more nodes, not to actually build a cbft-style queryable distributed index.
