### ISSUE TITLE
Is it possible to customize the id of the "cfg" document?

### ISSUE THREAD

**Issue by tleyden** [couchbaselabs/cbgt#11]
In our case, we'd like to call it _sync:cfg

**Comment by steveyen** [comment]
Yes, somewhere in your CfgCB initialization code, before passing it to the cbgt.Manager, invoke cfgCB.SetKeyPrefix("_sync:")

https://github.com/couchbaselabs/cbgt/blob/master/cfg_cb.go#L87

**Comment by tleyden** [comment]
Great!
