### ISSUE TITLE
Question: duplicate index created then deleted, why didn't pindexes spread out?

### ISSUE THREAD

**Issue by tleyden** [couchbaselabs/cbgt#14]
To reproduce:
- Start first sync gateway (sg1) with config params:
  - max_partitions_per_pindex: 512
  - bind_http: sg1
  - data_dir: `/root/cbgt`
- Add some documents via sync gw api
- Start second sync gateway (sg2) with config params:
  - max_partitions_per_pindex: 512
  - bind_http: sg2
  - data_dir: `/root/cbgt`

Here's the code we'd added to check for an existing index:

```
func (bucket CouchbaseBucket) checkCBGTIndexExists(indexName string) (bool, error) {

    _, indexDefsMap, err := CBGTManager.GetIndexDefs(false)
    if err != nil {
        return false, err
    }
    return (indexDefsMap[indexName] != nil), nil

}
```

but it didn't seem to work.  Even though the sg1 machine [created an index](https://gist.github.com/tleyden/a65d809bb489259876c0#file-sg1-logs-L20), when sg2 was brought online several minutes later, it [recreated an index with the same name](https://gist.github.com/tleyden/a65d809bb489259876c0#file-sg2-logs-L19)

At this point, it looks like sg1 [dropped both of its pindexes](https://gist.github.com/tleyden/a65d809bb489259876c0#file-sg1-logs-L474), and the remaining pindexes stayed on sg2.

My questions are:
- Any thoughts on why the `checkCBGTIndexExists` function didn't work?
- Why didn't one of the two pindexes remaining on sg2 spread out so that one was running on sg1?

**Comment by steveyen** [comment]
From chat with Traun and Adam, some links to relevant code...

https://github.com/couchbase/sync_gateway/tree/feature/distributed_index_issue_922

https://github.com/couchbase/sync_gateway/blob/feature/distributed_index_issue_922/src/github.com/couchbase/sync_gateway/base/bucket.go

One thing we found was that the code that checks whether an index already exists should specify a refresh parameter of true for the retrieving the index definitions.  That said, it's a bit mysterious why the 2nd node didn't see the first node's Cfg entries even after the 2nd node started 10 minutes later than the 1st node, and why the pindexes weren't spread out across the 2 nodes correctly.

Printing out the Cfg contents should be able to help future debugging.

**Comment by tleyden** [comment]
Changing the refresh=true didn't help.

Here are the logs from both sg1 (started first) and sg2 (started second):

https://gist.github.com/tleyden/7e146a61873135552cb9

Search for cfgMem to see the Cfg doc dumped out.  

It looks like there is a race between [this code](https://github.com/couchbaselabs/cbgt/blob/master/cfg_cb.go#L158) getting called and [checkCBGTIndexExists being called](https://gist.github.com/tleyden/7e146a61873135552cb9#file-sg1-L19)

Since checkCBGTIndexExists is called before the Cfg is loaded from the couchbase bucket, the indexDefs is nil.  Any thoughts?

**Comment by steveyen** [comment]
Yeah, looks like a race.  There's probably some proper way to do this of somehow waiting until cbgt.Manager/Cfg is properly initialized before checking the existence of and/or creating an index... and I'll research that.

But if you can't wait to make progress, perhaps that old standby of sleeping N seconds can be a temporary band-aid?

**Comment by tleyden** [comment]
Thanks!

**Comment by steveyen** [comment]
Next suggestion...

After initializng the Cfg, call it's Refresh() method before initializing the cbgt.Manager.

That _should_ do the trick (knock on wood).

**Comment by steveyen** [comment]
(Related, perhaps this is also a latent bug in cbft's usage of cbgt)

**Comment by steveyen** [comment]
(Regarding cbft, I've been wondering why we hadn't seen this issue in cbft, and the theory is that unlike sync-gateway, cbft doesn't try to existence-check and create an index ASAP.  Which leaves lots of time  for the cbgt in cbft to asynchronously setup a DCP stream in order to subscribe to cfg bucket changes and load in the Cfg on its own sweet time.)

**Comment by steveyen** [comment]
The race Traun discovered also explains why the the pindexes weren't spreading out on the addition of the 2nd sg-node.  When the 2nd sg-node started up, it read the (incorrect) Cfg entry on the available nodes (which was incorrectly empty due to the race), then 2nd sg-node added itself to the JSON, then 2nd sg-node wrote the updated JSON entry into the Cfg, and hence inadvertently removed the 1st sg-node's entry from the JSON listing of available nodes.

**Comment by tleyden** [comment]
> After initializng the Cfg, call it's Refresh() method before initializing the cbgt.Manager.

Will try this and get back to you

**Comment by tleyden** [comment]
> explains why the the pindexes weren't spreading out

Makes sense, thanks for writing this out!

**Comment by tleyden** [comment]
> After initializng the Cfg, call it's Refresh() method before initializing the cbgt.Manager.

This didn't seem to work.  Here are the logs:

https://gist.github.com/tleyden/659772b511faa9d0c80a

**Comment by tleyden** [comment]
Root cause (at least partial): https://github.com/couchbaselabs/cbgt/issues/18

**Comment by tleyden** [comment]
Fixing #18 seems to have fixed everything.  Logs: https://gist.github.com/tleyden/c4d38f5e9cc8a45da658
