### ISSUE TITLE
Question: does cbgt have it's own UI?

### ISSUE THREAD

**Issue by tleyden** [couchbaselabs/cbgt#16]
Got screenshots?

**Comment by steveyen** [comment]
<img width="1092" alt="screen shot 2015-08-05 at 11 16 05 am" src="https://cloud.githubusercontent.com/assets/30640/9095405/f6dc66b0-3b6b-11e5-8f6d-31b28478abf2.png">
<img width="1112" alt="screen shot 2015-08-05 at 11 15 43 am" src="https://cloud.githubusercontent.com/assets/30640/9095410/fb28ba16-3b6b-11e5-8898-0d6a560cceaa.png">
<img width="1071" alt="screen shot 2015-08-05 at 11 15 31 am" src="https://cloud.githubusercontent.com/assets/30640/9095413/fefe7c84-3b6b-11e5-9527-41f715d8ac1c.png">
<img width="1158" alt="screen shot 2015-08-05 at 11 15 09 am" src="https://cloud.githubusercontent.com/assets/30640/9095416/03ed81ae-3b6c-11e5-88dc-df7cdfe85a81.png">
<img width="818" alt="screen shot 2015-08-05 at 11 13 40 am" src="https://cloud.githubusercontent.com/assets/30640/9095420/079dfa4a-3b6c-11e5-83d0-0efb34513ddc.png">

**Comment by steveyen** [comment]
<img width="913" alt="screen shot 2015-08-05 at 12 23 10 pm" src="https://cloud.githubusercontent.com/assets/30640/9095565/c95bf484-3b6c-11e5-911f-63cac2ef167a.png">

**Comment by steveyen** [comment]
Those screenshots are from cbft, but the meat of the UI comes from cbgt.

Similarly, cbmirror also has a UI, but also just reuses most of it from cbgt.

So, cbft and cbmirror are pretty good sample codebases to look at to see how to use cbgt's REST / UI api's...
- http://godoc.org/github.com/couchbaselabs/cbgt/rest#InitRESTRouter
- http://godoc.org/github.com/couchbaselabs/cbgt/rest#InitStaticRouter

Documentation on the REST API (via the online cbft technical docs) is available here...

http://labs.couchbase.com/cbft/api-ref/

**Comment by steveyen** [comment]
<img width="871" alt="screen shot 2015-08-05 at 12 28 51 pm" src="https://cloud.githubusercontent.com/assets/30640/9095701/949815b0-3b6d-11e5-9084-63e070db6ef6.png">

**Comment by tleyden** [comment]
> Documentation on the REST API (via the online cbft technical docs) is available here...

Can you add a link to that to the README?

**Comment by steveyen** [comment]
> > Documentation on the REST API (via the online cbft technical docs) is available here...
> > Can you add a link to that to the README?

Should be in that comment, but here it is again: http://labs.couchbase.com/cbft/api-ref/

(Or, did you mean something else?)

**Comment by tleyden** [comment]
I sent a PR

**Comment by steveyen** [comment]
Some more UI screenshots, showing off some replica placement policies...

Here, you can see the index partitions (pindexes) have 2nd replica placed near the 1st pindex on the same "rack"...
<img width="1014" alt="screen shot 2015-08-12 at 4 06 18 pm" src="https://cloud.githubusercontent.com/assets/30640/9238997/4a3053b2-410c-11e5-8b38-d139d8b8d312.png">

Here, you can see the policy where 2nd replica is placed on a different rack than the 1st pindex instances...
<img width="1001" alt="screen shot 2015-08-12 at 4 06 41 pm" src="https://cloud.githubusercontent.com/assets/30640/9238999/4a318872-410c-11e5-974e-ef3d6fe45502.png">

Here's a screen shot of the list of nodes, where it's showing the optional rack and zone column for each node...
<img width="978" alt="screen shot 2015-08-12 at 4 06 55 pm" src="https://cloud.githubusercontent.com/assets/30640/9238998/4a311f4a-410c-11e5-8de0-8baa724cf368.png">
