### ISSUE TITLE
SetKeyPrefix bug

### ISSUE THREAD

**Issue by tleyden** [couchbaselabs/cbgt#18]
From @steveyen 

> the code is initializing using cmd.MainCfg()...
> which calls Load()...
> https://github.com/couchbaselabs/cbgt/blob/master/cmd/main_cfg.go#L96
> ...and that breaks the assumption mentioned in the comments about needing to call SetKeyPrefix() before doing anything else
> ah, but that might not be the real bug...
> i see the implementation of Refresh()...
> is making a new CfgCB
> https://github.com/couchbaselabs/cbgt/blob/master/cfg_cb.go#L194
> and it's not copying over the cfgKey
> boom, that's it

**Comment by steveyen** [comment]
This should fix it: commit 411f1e7e2d5d2d599126ec9257fea7f6b17d973e
