### ISSUE TITLE
proposed API change: NewCfgCB and SetKeyPrefix

### ISSUE THREAD

**Issue by steveyen** [couchbaselabs/cbgt#19]
The CfgCB.SetKeyPrefix() API is kind of janky, where it needs to be called before doing anything with a brand-new CfgCB.

This has already shown to lead to one race issue (issue 18).

Instead, the (breaking API) proposal is the key prefix should added as a parameter of the NewCfgCB() constructor, and hence also of the cmd.MainCfg() and cmd.MainCfgCB() API's.  It'll be cleaner.

Apps that'll probably break with this cbgt API change would include cbft, cbmirror and probably the prototype sync-gateway.

cc: @tleyden

**Comment by steveyen** [comment]
Ended up deprecating SetKeyPrefix() and also adding a brand new NewCfgCBEx() API where the key prefix can be passed in in NewCfgCBEx()'s options parameter in one shot.  So no more race issues.

**Comment by tleyden** [comment]
Thanks, I put a note in the Sync Gw code to move away from SetKeyPrefix
