### ISSUE TITLE
Getting same Manager UUID on different instances

### ISSUE THREAD

**Issue by tleyden** [couchbaselabs/cbgt#2]
I'm initializing CBGT in two separate processes, with separate Data Directories, and they are ending up getting the same manager UUID.

It looks like it's because this code to generate the UUID:

```
func NewUUID() string {
    val1 := rand.Int63()
    val2 := rand.Int63()
    uuid := fmt.Sprintf("%x%x", val1, val2)
    return uuid[0:16]
}
```

is never seeding the random number generator.

Adding this seems to work around the problem:

```
func init() {
    rand.Seed(time.Now().UTC().UnixNano())
}
```

though I wonder if there are even better solutions.  Might be worth looking at a UUID generator library to see what they do.  The one I've used in the past is https://github.com/nu7hatch/gouuid

**Comment by steveyen** [comment]
Great find.  I see that cbft does that seeding, which explains why I wasn't seeing this issue...

  https://github.com/couchbaselabs/cbft/blob/master/cmd/cbft/main.go#L73

**Comment by tleyden** [comment]
Do you want me to send a PR with the change mentioned in the first comment?

**Comment by steveyen** [comment]
> Do you want me to send a PR with the change mentioned in the first comment?

Sure, that'd be cool!
