### ISSUE TITLE
Question: getting vbucket partition map

### ISSUE THREAD

**Issue by tleyden** [couchbaselabs/cbgt#21]
Is there a way to get the Map of pindex -> vbucket from cbgt?

Is that static?  When does that change?

**Comment by steveyen** [comment]
If you know the name of the PIndex (with that hash suffix), then you can call...

```
http://godoc.org/github.com/couchbaselabs/cbgt#Manager.GetPIndex
```

Or, if you want all PIndexes, you can call...

```
http://godoc.org/github.com/couchbaselabs/cbgt#Manager.GetPlanPIndexes
```

Either way will eventually get you to a PIndex struct or a PlanPIndex struct that has a SourcePartitions field.  The SourcePartitions is a string that's a comma-separated list of vbucket ID's for that PIndex.

The PIndex struct is pretty much static, where an index is split or partitioned into multiple PIndexes at the creation/definition time of the index.

The PlanPIndex is dynamic, and represents the assignment of a PIndex to nodes.  It changes whenever the node topology changes and the planner decides to move or reassign a PIndex amonst nodes.

**Comment by tleyden** [comment]
> It changes whenever the node topology changes and the planner decides to move or reassign a PIndex amonst nodes.

In our testing, we've been able to add Sync Gateway nodes and have have the Pindexes spread to the newly added node.  What about removing Sync Gateway nodes?  Is there a way we can tell CBGT "Hey, we're going to go away, reassign my Pindexes to other nodes"?

**Comment by steveyen** [comment]
> In our testing, we've been able to add Sync Gateway nodes and have have the Pindexes spread to the newly added node.

Very cool!  Exciting!

> What about removing Sync Gateway nodes? Is there a way we can tell CBGT "Hey, we're going to go away, reassign my Pindexes to other nodes"?

Yep, please see response on other issue here: https://github.com/couchbaselabs/cbgt/issues/22

**Comment by tleyden** [comment]
I'll give it a shot, thanks!
