### ISSUE TITLE
API to eject a node, even a remote node

### ISSUE THREAD

**Issue by steveyen** [couchbaselabs/cbgt#26]
When some administrator or monitoring system notices that a node is down, they may ultimately want to invoke some API that ejects a node (possibly a remote node) from the cluster.

**Comment by tleyden** [comment]
This should be idempotent -- if 4 nodes try to eject a node at approximately the same time, should not ensue chaos.

**Comment by steveyen** [comment]
@tleyden Good point!

Also, for the future me, a pointer to some relevant node unregistration code that'll probably be refactored...

https://github.com/couchbaselabs/cbgt/blob/master/manager.go#L336

**Comment by steveyen** [comment]
Please see cbgt commit 6583cc1

The approach is that any node can invoke the following...

```
cbgt.CfgRemoveNodeDef(cfg, cbgt.NODE_DEFS_WANTED,
    uuidOfNodeToEject, cbgt.VERSION)
cbgt.CfgRemoveNodeDef(cfg, cbgt.NODE_DEFS_UNKNOWN,
    uuidOfNodeToEject, cbgt.VERSION)
```

...and, then the planner should automatically re-plan the PIndex assignments to remaining nodes.

If there's concurrent removal attempts from racing monitoring systems, then the CfgRemoveNodeDef should return an error on the "losers of the race", which the app can handle (like, re-read the cluster's status and based on the perceived situation, perhaps try again after some backoff time).

**Comment by tleyden** [comment]
Does `uuidOfNodeToEject` correspond to the [Manager UUID](https://github.com/couchbaselabs/cbgt/blob/master/manager.go#L50)?

**Comment by steveyen** [comment]
> Does uuidOfNodeToEject correspond to the Manager UUID?

Yes, that's right.

**Comment by tleyden** [comment]
One more question.  It looks like it needs a `kind` parameter, which can be one of two values:
- `NODE_DEFS_WANTED`
- `NODE_DEFS_KNOWN`

Should I be passing in `NODE_DEFS_KNOWN`?

**Comment by steveyen** [comment]
Recommendation is use both, so call it twice.
