### ISSUE TITLE
API to re-register a node and/or propagate Cfg errors

### ISSUE THREAD

**Issue by steveyen** [couchbaselabs/cbgt#27]
One case brought up from @tleyden is if there's a network partition, the monitoring scripts might kick in and eject nodes out a cluster.

But the ejected nodes actually never went down (their processes kept on running).

On healing from the partition, the ejected (but still running) nodes won't necessarily re-enter the cluster, as they probably think they never left.

Some raw notes:

unhandled case in the code... 
- on healing back after network partition...
- during the network partition
  -- let's say some heartbeat/auto-failover/monitoring-system kicked a node out
  -- so, it unregistered the node from the Cfg
- when healing from a partition
- the (still-running, never-died, never-restarted) "re-joined" node never updates the Cfg
- and so it never re-registers in the Cfg
- if the process never died, never restarted

related to this case, the cbgt parts might be seeing Cfg errors, but not really propagating those errors to the app
- handling those errors will be app-specific
- but we're missing the callbacks up to the app today
- e.g., some apps might want to auto-reregister (sync-gw?)
  -- think about simplified API for those apps that want auto-reregister
- some apps might want to just stay kicked out (cbft?)

**Comment by steveyen** [comment]
Two parts...

On the part about forcefully re-registering a node, the API to do that exists already...

```
http://godoc.org/github.com/couchbaselabs/cbgt#Manager.Register
```

Just invoke mgr.Register("wantedForce") whenever you want to forcefully re-register a node back into the Cfg.

But, on part 2, when do you call the above Register("wantedForce")?  The relevant line of cbgt code that needs to likely change is right here, where it should do something useful like callback to the app instead of just logging a message...

```
https://github.com/couchbaselabs/cbgt/blob/master/cfg_cb.go#L236
```

The API proposed change is then to add an Error field to the CfgEvent struct...

```
http://godoc.org/github.com/couchbaselabs/cbgt#CfgEvent
```

When an application Subscribe()'s to a Cfg, the app gets a bunch of CfgEvent's...

```
https://github.com/couchbaselabs/cbgt/blob/master/cfg.go#L35
```

And, with this proposed API addition (existing apps shouldn't hopefully break), whenever there's an underlying Cfg error, they'll see a CfgEvent on their subscriptions that as empty ("") Key field, 0 for CAS, and non-nil Error...

```
CfgEvent{
    Key: "",
    CAS: 0,
    Error: fmt.Errorf("got some error from some cfg communication problem or something")
}
```

When the Cfg subsystem "heals" (the network partition is fixed) and the Cfg subsystem regains connectivity, then the application will see regular CfgEvents{}'s so it can know to re-register as "wantedForce" if it needs.

**Comment by tleyden** [comment]
> and the Cfg subsystem regains connectivity, then the application will see regular CfgEvents{}'s so it can know to re-register as "wantedForce" if it needs.

Wouldn't it be able to check the Cfg at this point and see that it's no longer listed as an active node?  Based on that alone, it would know that it might need to re-add itself.  I'm just thinking that this might be simpler than having to remember previous Cfg errors.

**Comment by steveyen** [comment]
Yeah, I guess the app should be able to do that Cfg active-node check and make the right call on whether to re-add.

I say "app" because I think this proposal makes the most sense for stateless apps (like sync-gateway) as opposed to apps with lots of persisted local-storage state (like cbft with its indexes & cbmirror with its DCP data storage, where apps like that with lots of locally persisted state probably won't like things getting moved around a lot).

**Comment by steveyen** [comment]
See commit 9ebf42a

If you want to subscribe to errors, with the commit, you can now call Cfg.Subscribe() with an empty key ("").
