### ISSUE TITLE
Autofailover subpackage

### ISSUE THREAD

**Issue by tleyden** [couchbaselabs/cbgt#28]
Add a new subpackage `cbgt/autofailover` which would allow an API similar to the following:

```
func main() {

  ...

  cfg := ... start a Cfg...

  mgr := cbgt.NewManager(..., cfg, bucketName)

  mgr.Start(...)

  hbOptions := { ...

    HeartBeatTime: ... e.g., every 5 seconds

    StaleHeartBeatTimeout: ... haven't heard a heartBeat update /* 30 secs */

    ...

  }

  ...

  autoFailover := hb.StartAutoFailover(couchbaseURL/auth,

     bucketName, "someKeyPrefix", mgr, hbOptions)

     ==> calls cbheartbeat

  ...

  autoFailover.Stop()

}
```

where he "heartbeat grunt work" would be factored out (or easily refactorable) into a separate lib.

**Comment by steveyen** [comment]
Hi @tleyden 

Just to get on same page, I see it as two subpackages (you might already be thinking the same thing)...
- cbheartbeat -- detects that a node is down; I thinking this seems pretty generic, so perhaps can go into someplace like couchbaselabs/cbheartbeat (i.e., it's not really tied to cbgt).
- autofailover -- provides one way of handling a "node looks like it's down" event by removing a cbgt node from a cluster.  That's fine, imho, to live in couchbaselabs/cbgt/autofailover

**Comment by tleyden** [comment]
Yep, agreed.  Factored out a new ticket.

**Comment by tleyden** [comment]
Preliminary test results -- it doesn't seem to be moving around the pindexes after calling `CfgRemoveNode`.  Here are the logs: https://gist.github.com/tleyden/f9d9c86077ba63ba3cb5
