### ISSUE TITLE
Running into auth related errors

### ISSUE THREAD

**Issue by tleyden** [couchbaselabs/cbgt#3]
When I ran a local sync gateway connecting to a local couchbase server, I didn't see any auth errors.  However on AWS with sync gateway and couchbase server on different machines, I'm seeing this error:

```
2015-07-24T23:45:47.231Z DCP: Error creating CBGT index: manager_api: failed to connect to or
retrieve information from source, sourceType: couchbase, sourceName: bucket-1, sourceUUID:
8b89f4f79e13c901ce95ff843febc5dc, err: feed_cb: DataSourcePartitions/couchbase connection failed,
server: http://ip-10-158-136-92.ec2.internal:8091/, poolName: default, bucketName: bucket-1, 
sourceType: couchbase, sourceParams: "", err: HTTP error 401 Unauthorized getting "http://ip-10-158-
136-92.ec2.internal:8091/pools": , please check that your authUser and authPassword are correct and 
that your couchbase server ("http://ip-10-158-136-92.ec2.internal:8091/") is available
```

If I switch Sync Gateway back to using "normal" DCP as opposed to CBGT, I don't see any auth related errors, so it seems to be related to the way I'm using CBGT.  At this point, I've done nothing in the Sync Gateway CBGT related code as far as auth.  What should I be doing, if anything?

I did notice this comment in defs.go:

>   // NOTE: Any auth credentials to access datasource, if any, may be
>   // stored as part of SourceParams.

can you expand on that a bit or provide an example?

**Comment by tleyden** [comment]
Also, not sure how useful this is .. but regarding the "normal" DCP (non-CBGT) auth handling in Sync Gateway -- here are some relevant code snippets where it sets up the auth object that gets passed to `cbdatasource.NewBucketDataSource`:
- [bucket.StartDCPFeed()](https://github.com/couchbase/sync_gateway/blob/4e6a4ff8e547445a1eb54179f843c24d5802a002/src/github.com/couchbase/sync_gateway/base/bucket.go#L191-L200)
- [bucket.getDcpAuthHandler()](https://github.com/couchbase/sync_gateway/blob/4e6a4ff8e547445a1eb54179f843c24d5802a002/src/github.com/couchbase/sync_gateway/base/bucket.go#L224-L232)

**Comment by steveyen** [comment]
Hi Traun,

The SourceParams mentioned in that defs.go comment is a string that's parsed as JSON; in this case, the SourceParams string will be parsed as a JSON encoded CBGT DCPFeedParams struct...

   https://github.com/couchbaselabs/cbgt/blob/master/feed_dcp.go#L111

There, you can see the AuthUser and AuthPassword fields that you can set ("authUser" and "authPassword" in the JSON).

Related to your sync-gateway (non-CBGT) code snippets, here's some of the equivalent or related code in feed_dcp in CBGT, where you can see CBGT is invoking cbdatasource similar to how sync-gateway is invoking cbdatasource..

```
https://github.com/couchbaselabs/cbgt/blob/master/feed_dcp.go#L180
https://github.com/couchbaselabs/cbgt/blob/master/feed_dcp.go#L151
```

**Comment by tleyden** [comment]
@steveyen after digging into this with @adamcfraser, the problem seems to be that:
- The bucket we are connecting to has auth enabled, but no password set
- In the sync gateway codebase / config, we're doing nothing regarding auth and just expecting it to work
- Since it's not using the bucket name as the username by default, the auth doesn't work

Proposed fix: use the bucket name as the username if no username is given by the app using cbgt as a library.

**Comment by tleyden** [comment]
Relevant comment in the [sync gateway codebase](https://github.com/couchbase/sync_gateway/blob/d0d514107b60cf56b19aa5089306de06459cbf3b/src/github.com/couchbase/sync_gateway/base/dcp_feed.go#L39-L46)

```
// GetCredentials is used when cbdatasource makes a new bucket connection, based on approach we're
// using for our other bucket connections (via go-couchbase pools.go authHandler()).
// Background: After hitting an auth issue when connecting to a new cbdatasource bucket with the
// standard username/password authenticator, I talked to Steve Yen and he tipped me off about the
// default bucketname-as-username handling, and figured out that go-couchbase was doing that for us
// for our usual bucket handling.
// Reviewed with Steve and he said that the auth handling in couchbase server is undergoing changes
// as part of Sherlock, so we may need to revisit once they've stabilized on an approach.
```
