### ISSUE TITLE
Adding auth handler when it shouldn't?  (when connecting to default bucket)

### ISSUE THREAD

**Issue by tleyden** [couchbaselabs/cbgt#32]
I'm noticing an issue which I traced to go-couchbase adding Basic Auth with an empty username/pass when I'm trying to connect to the default bucket:  https://github.com/couchbase/go-couchbase/issues/62

However, I'm wondering if this isn't a CBGT bug, where it's passing go-couchbase a non-nil AuthHandler whereas it should be passing nil.

In the call to `cmd.MainCfg()`, I'm passing a `connect` parameter: `couchbase:http://localhost:8091`

**Comment by steveyen** [comment]
cc'ing @nimishzynga

**Comment by steveyen** [comment]
Ahhh, I'm realizing something: are you trying to use the default bucket as your cfg bucket?  (Which is something that hadn't previously popped into my head as something that folks would try to do.)

Thanks,
Steve

**Comment by tleyden** [comment]
Yep, it's the default bucket .. and that's where the cfg is being stored.

**Comment by steveyen** [comment]
Hi Traun, the strange thing is that it's working for me for cbft.

That is, when I use the default bucket, by trying the cmd-line parameter of either ...

```
-cfg=couchbase:http://default@localhost:8091
```

or...

```
-cfg=couchbase:http://localhost:8091
```

...in cbft, it works.

cbft also calls the cmd.MainCfg() helper function, which eventually invokes cmd.MainCfgCB(), which has this hunk of code that defaults to "default"...

```
https://github.com/couchbaselabs/cbgt/blob/master/cmd/main_cfg.go#L86
```

**Comment by steveyen** [comment]
One other thing to clarify, there are several DCP streams at play here...

A - DCP used to subscribe to Cfg changes

B - DCP used for the PIndexes

Wondering if you're having troubles with A or B or both?

Thanks,
Steve

**Comment by tleyden** [comment]
As a note to myself, adding steps to repro this:
- Sync Gateway commit c1ba2c8a28e8c3db45a378ce4b97da7d49776ed6
- CBGT commit 0b98f1071ebf28a6fd2b7bec88ee5ffbb6dd235f
- Sync Gateway config: https://gist.github.com/tleyden/5cb8816a2e6768571b27

**Comment by tleyden** [comment]
I added more logging, and here is what Sync Gw is currently passing CBGT in terms of information to connect to the CB bucket:

```
2015/08/31 12:36:05 Calling cbgt.NewCfgCBEx() with http://localhost:8091 and bucket default
2015/08/31 12:36:06 Calling cbgt.NewManager() with server: http://localhost:8091
```

Full logs here: https://gist.github.com/tleyden/33a2f36f8ca96a8bb7cc#file-gistfile1-txt-L23-L24

Code snippet here: https://github.com/couchbase/sync_gateway/blob/feature/distributed_index_autofailover/src/github.com/couchbase/sync_gateway/rest/server_context.go#L304-L401

Does this look like it's passing the correct things to CBGT?

**Comment by tleyden** [comment]
> Wondering if you're having troubles with A or B or both?

I'm not sure how I can tell, since I'm using the default bucket in both cases.

**Comment by steveyen** [comment]
Thanks - from the latest logs, the "feed_dcp" log messages are telling me it's problems with DCP connection for the PIndexes (so problem with B).

```
 2015/08/31 12:36:06 feed_dcp: OnError, name: default_5fa3284f923c655c: bucketName: default, bucketUUID: 9781c75a939f18c593856a4fb125333b, err: HTTP error 401 Unauthorized getting "http://localhost:8091/pools":
 2015/08/31 12:36:06 feed_dcp: OnError, name: default_5fa3284f923c655c: bucketName: default, bucketUUID: 9781c75a939f18c593856a4fb125333b, err: could not connect to any serverURL: []string{"http://localhost:8091"}
```

My guess for a fix/workaround is to do that "authUser": "default" maneuver (instead of (what I think you're using)... "authUser": "").

**Comment by tleyden** [comment]
> My guess for a fix/workaround is to do that "authUser": "default" maneuver (instead of (what I think you're using)... "authUser": "").

Would that be done somewhere in the call to NewManager()?  Not sure where to make that workaround.

https://github.com/couchbase/sync_gateway/blob/feature/distributed_index_autofailover/src/github.com/couchbase/sync_gateway/rest/server_context.go#L362-L374

**Comment by tleyden** [comment]
I can confirm that this modification in dcp_feed.go works around the issue:

```

// NewDCPFeed creates a new, ready-to-be-started DCP feed.
func NewDCPFeed(name, indexName, url, poolName,
    bucketName, bucketUUID, paramsStr string,
    pf DestPartitionFunc, dests map[string]Dest,
    disable bool) (*DCPFeed, error) {

    params := NewDCPFeedParams()
    if paramsStr != "" {
        err := json.Unmarshal([]byte(paramsStr), params)
        if err != nil {
            return nil, err
        }
    }

    params.AuthUser = "default"   // <---- workaround!
```

 Now I'm tracing up the stack to see where I can fix this in the Sync Gateway code.  Any hints would be welcome.

**Comment by steveyen** [comment]
It'd be in the mgr.CreateIndex(), with the sourceParams parameter.  Which should be JSON that conforms to...

https://github.com/couchbaselabs/cbgt/blob/master/feed_dcp.go#L115

**Comment by tleyden** [comment]
Ok thanks

**Comment by tleyden** [comment]
I can confirm that the following workaround in Sync Gateway's dcp_feed.go file fixes the issue:

```
// GetCredentials is used when cbdatasource makes a new bucket connection, based on approach we're
// using for our other bucket connections (via go-couchbase pools.go authHandler()).
// Background: After hitting an auth issue when connecting to a new cbdatasource bucket with the
// standard username/password authenticator, I talked to Steve Yen and he tipped me off about the
// default bucketname-as-username handling, and figured out that go-couchbase was doing that for us
// for our usual bucket handling.
// Reviewed with Steve and he said that the auth handling in couchbase server is undergoing changes
// as part of Sherlock, so we may need to revisit once they've stabilized on an approach.
func (a dcpAuth) GetCredentials() (string, string, string) {

    username := a.Username
    password := a.Password

    // as long as it's not the default bucket, if the username is empty
    // then set the username to the bucketname.  (if it's the default bucket, the
    // username should just be empty rather than "default")
    if a.Username == "" && a.BucketName != "default" {
        username = a.BucketName
    }

    // if the username is empty, then the password should be empty too
    if username == "" {
        password = ""
    }

    // if it's the default bucket, then set the username to "default"
    // workaround for https://github.com/couchbaselabs/cbgt/issues/32#issuecomment-136481228
    if a.BucketName == "" || a.BucketName == "default" {
        username = "default"
    }

    return username, password, a.BucketName

}
```

**Comment by tleyden** [comment]
At the very least, I think in go-couchbase pools.go:

```
// AuthHandler is a callback that gets the auth username and password
// for the given bucket.
type AuthHandler interface {
    GetCredentials() (string, string, string)
}
```

Should get an upgrade in the comment that specs out the contract "if using the 'default' bucket, the username should be 'default'".  Either that or the more generic "the username returned by this should never be empty".

**Comment by steveyen** [comment]
added an issue into go-couchbase project: https://github.com/couchbase/go-couchbase/issues/64
