### ISSUE TITLE
Mysterious transient docs

### ISSUE THREAD

**Issue by tleyden** [couchbaselabs/cbgt#41]
From https://github.com/couchbase/sync_gateway/issues/1089

>  On SG startup when _sync:cfg hasn't yet been defined, a lot of apparently transient docs show up on the feed with docIDs like 'k21049', 'k021', 'k22025' etc. Don't see corresponding docs/traffic in the bucket, so they appear to be artificially added to the feed by cbgt. They get rejected (with error) because they don't have sync metadata, but need to understand whether this would cause problems for cbgt if users created docs with these IDs (in the case where the source bucket is used for cfg storage).

Do those docsID's look like they are from CBGT?

**Comment by steveyen** [comment]
Nope, cbgt doesn't generate any docID's, and just forwards along what it gets from DCP.  So those keys are likely just docs that are in the bucket.  So, it would be surprising that you...

```
"Don't see corresponding docs in the bucket..."
```

One interesting part, though, is you mentioned...

   "On SG startup when _sync:cfg hasn't yet been defined, a lot of apparently transient docs show up..."

What does that mean?

thanks,
steve

**Comment by steveyen** [comment]
Closing this as I think the corresponding checkbox on https://github.com/couchbase/sync_gateway/issues/1089 seems to have been closed.
