### ISSUE TITLE
log ops that take >1 second

### ISSUE THREAD

**Issue by steveyen** [couchbaselabs/cbgt#43]
KV engine logs slow ops that take > 1 second, which has proven helpful for production issue diagnosis

**Comment by mschoch** [comment]
You may want to consider using Dustin's "yellow" library for this.

https://github.com/dustin/yellow

**Comment by steveyen** [comment]
Looks like it was too simple to need another library.  commit 0d323e07

THere's a new optional cmd-line flag, called "options", which allow for open-ended key=value parameters.  Example usage of the "slowQueryLogTimeout" option...

```
./cbft ... -options=slowQueryLogTimeout=100ms
./cbft ... -options=slowQueryLogTimeout=5s
./cbft ... -options=slowQueryLogTimeout=10s
```

When there's a slow query, we'll see output in the log like...

```
2015/09/22 21:34:47 slow-query: index: bsa, query: {"q":"beer","indexName":"bsa","size":10,"from":0,"explain":true,"highlight":{},"query":{"boost":1,"query":"beer"},"fields":["*"],"ctl":{"consistency":{"level":"","vectors":{}},"timeout":0}}, duration: 86.558171ms, err: <nil>
```
