### ISSUE TITLE
Which pindexes in CFG document are loaded vs ignored?

### ISSUE THREAD

**Issue by tleyden** [couchbaselabs/cbgt#44]
While debugging https://github.com/couchbase/sync_gateway/issues/1129, I ran into a question.

With [this CFG file](https://gist.github.com/tleyden/99ef592bcdf0ba348612), and the following pindex directories on the file system (Im using just one Sync Gateway node)

```
bucket-2_2504fb2479c69f76_acbbef99.pindex
bucket-2e8328ddd84d1020bd82d72ebf09b05e3_22067264f250ba4f_b7ff6b68.pindex
```

I'm seeing logs of the pindexes that exist on the filesystem being loaded:

```
2015/09/14 15:44:44 manager: opening pindex: /Users/tleyden/Development/sync_gateway/cbgt_data/bucket-2_2504fb2479c69f76_acbbef99.pindex
2015/09/14 15:44:44 manager: opening pindex: /Users/tleyden/Development/sync_gateway/cbgt_data/bucket-2e8328ddd84d1020bd82d72ebf09b05e3_22067264f250ba4f_b7ff6b68.pindex
```

Here's my question: does it ignore the Pindexes in the CFG if they cannot be found on the filesystem?  Just curious, what's the logic here?

Also, any insights or tips on https://github.com/couchbase/sync_gateway/issues/1129 would be greatly appreciated!

**Comment by steveyen** [comment]
At process startup time (Manager.Start() time), cbgt will open all the pindexes that it finds in the dataDir...

   https://github.com/couchbaselabs/cbgt/blob/master/manager.go#L361

But, it doesn't hookup data feeds (DCP streams) to those pindexes yet.

So, those log entries looks like normal behavior.

> Here's my question: does it ignore the Pindexes in the CFG if they cannot be found on the filesystem? Just curious, what's the logic here?

Nope; instead, those PIndexes will be cleaned up by a later janitor run (where the janitor will close or remove any extra pindexes that aren't in the Cfg, and the janitor will create any missing pindexes that are in the Cfg but not yet existing on the node).

Will comment separately on couchbase/sync_gateway#1129 if I got anything.
