### ISSUE TITLE
How do I customize the bucket that it stores it's configuration in?

### ISSUE THREAD

**Issue by tleyden** [couchbaselabs/cbgt#9]
Currently I have three buckets defined on my couchbase server:
- bucket-1
- bucket-2
- default

And CBGT is storing the `cfg` document in the `default` bucket, but I want it to store it in `bucket-1`.  Where do I configure this?

**Comment by tleyden** [comment]
It looks like it's currently [hardcoded](https://github.com/couchbaselabs/cbgt/blob/master/cmd/main_cfg.go#L86) to the `default` bucket.

**Comment by steveyen** [comment]
For cbft, it's configurable via the cmd-line using the "-cfg" flag.  Like...

```
couchbase:http://my-cfg-bucket@127.0.0.1:8091
```

So, in your case:

```
couchbase:http://bucket-1@127.0.0.1:8091
```

Or, if you've also a password, like...

```
couchbase:http://bucket-1:[PASSWORD]@127.0.0.1:8091
```

Here's some relevant cmd-line parsing code in cbft...

```
https://github.com/couchbaselabs/cbft/blob/master/cmd/cbft/main_flags.go#L84
```

Which eventually leads to this getting invoked...

```
https://github.com/couchbaselabs/cbgt/blob/master/cmd/main_cfg.go#L39
```
